# -*- mode: org; coding: utf-8-unix; ispell-dictionary: "spanish"; org-hide-emphasis-markers: t; eval: (auto-fill-mode); eval: (fci-mode) -*-

* Método ManBand

Es nuestra actividad habitual nos encontramos gestionando un gran número de
tareas de naturaleza muy diferente. Esta situación genera un gran estrés por lo
que se hace necesaria una forma de gestión que nos ayude disminuir este estrés
afrontando eficientemente el desempeño de las tareas.

Existen numerosas metodologías que han demostrado su efectividad en la gestión
de tareas, así como multitud de herramientas de bajo o ningún coste que
habitualmente se sitúan en la nube.

Precisamente por esta oferta tan abundante, es complicado definir un marco
concreto y único que nos ayude a la gestión de tareas sin que tengamos que
emplear mucho tiempo en el propio aprendizaje y uso de estas metodologías y
herramientas.

En mi caso, llevo enfrentándome a esta problemática desde hace años, tanto en el
ámbito personal como en el profesional. Durante todos estos años he ido
adaptando metodologías y herramientas a mis necesidades que, por otro lado, son
las mismas para otros muchos.

En concreto, he desarrollado un sencillo método basado en conceptos y
metodologías existentes, como GTD y kanban, que he puesto en práctica sobre
varias herramientas como [[https://www.wunderlist.com/][wunderlist]], [[https://www.rememberthemilk.com/][rememberthemilk]], [[https://trello.com/][trello]] y [[https://www.gnu.org/software/emacs/][Emacs]] ([[https://orgmode.org/][org]]).

A este método lo he denominado *manband* u *hombre orquesta* ya que es la principal
sensación que siento cuando me enfrento a la realización de múltiples acciones
que nada tienen entre sí. Gestionar todas esas tareas es como tocar varios
instrumentos a la vez.

Lo cierto es que llevo utilizando este método desde hace muchos años y me ha
servido, y me sirve, para gestionar eficientemente situaciones con muchas tareas
tanto en el ámbito personal como en el profesional.

Este repositorio contiene una [[http://goyoambrosio.com/manband][presentación del método manband]] y de los conceptos
y metodologías en los que se basa.

La presentación está basada en HTML por lo que puede ser visualizada en
cualquier navegador. Está basada en [[https://revealjs.com][Reveal.js]] y ha sido escrita en modo [[https://orgmode.org/][org]] de
[[https://www.gnu.org/software/emacs/][Emacs]] para ser exportada con [[https://github.com/yjwen/org-reveal][org-reveal]]. Un efecto colateral de la misma es que
puede servir de ejemplo para aquellos interesados en estas herramientas.

Espero que te sea de utilidad.

Gregorio Ambrosio (Goyo AC)


