# -*- mode: org; coding: utf-8-unix; ispell-dictionary: "spanish"; org-hide-emphasis-markers: t; eval: (auto-fill-mode); eval: (fci-mode) -*-


# #+BEGIN_abstract
# This is the abstract
# #+END_abstract


* Header Information                                               :noexport:

** Identification

# [[https://orgmode.org/manual/Export-settings.html][Export settings]]
#+TITLE: Document title
#+SUBTITLE: Document subtitle
#+DESCRIPTION: Document description
#+KEYWORDS: keywords separated by comma
# Use keybind C-c . or C-c < or free format like "Saturday 9th, 2019"
#+DATE: 
#+AUTHOR: Gregorio Ambrosio Cestero
#+EMAIL: goyoac@gmail.com
#+LANGUAGE: en

** General settings

#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.2.2 (Org mode 9.1.14)

#+OPTIONS: ':nil *:t -:t ::t <:t H:6 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:t f:t inline:t num:t p:nil pri:nil prop:t stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:nil |:t

# #+STARTUP: hidestars
# #+STARTUP: hideblocks
# #+STARTUP: nohideblocks
#+STARTUP: overview
#+STARTUP: indent
#+STARTUP: logdrawer

#+COLUMNS: %25ITEM %TAGS %TODO

 Keywords for file-local settings. The keywords after the vertical bar (or the
 last keyword if no bar is there) must always mean that the item is in its final
 state. Use C-c C-c with the cursor still in the line to make the changes known
 to Org mode
 #+TODO: TODO(t) NEXT(n) STARTED(s!) WAITING(w@/!) SOMEDAY(o) PROJ(p)| DONE(d!) CANCELLED(c@)

# TOC related
# #+OPTIONS: toc:t          include all levels in TOC
# #+OPTIONS: toc:2          only include two levels in TOC
# #+OPTIONS: toc:nil        no default TOC at all

# To move the TOC to a different location:
# #+OPTIONS: toc:nil        no default TOC
# ...
# #+TOC: headlines 2        insert TOC here, with two headline levels

# Use the TOC keyword to generate list of tables (resp. all listings) with captions.
# #+TOC: listings           build a list of listings
# #+TOC: tables             build a list of tables

** Export settings
*** ODT

 # [[https://orgmode.org/manual/ODT-specific-export-settings.html][ODT specific export settings]]
 # Style file application does not work fine for me. Apply with Load Style after
 # file creation.
 # #+ODT_STYLES_FILE: ~/cloud/Dropbox/DOCUMENTS/TEMPLATES/ODT/my_odt_template.odt
 # [[https://orgmode.org/manual/ASCII_002fLatin_002d1_002fUTF_002d8-export.html#ASCII_002fLatin_002d1_002fUTF_002d8-export][ASCII specific export setting]] (also for ODT)
 # #+DESCRIPTION and #+KEYWORDS are included as metadata in the aoutput file.


 # Abstract does not work when export in ODT format. Use it for Latex
 # #+BEGIN_ABSTRACT
 # Abstract
 # #+END_ABSTRACT
 # #+TOC: headlines 2

*** Code

 # To avoid evaluating code on export use the following header argument:
 #+PROPERTY: header-args :eval never-export

*** Pandoc

 #+BEGIN_COMMENT
 # Useful commands
 # Pandoc ignores some headers options (as PROPERTIES). Use export (C-c-e o o) instead.
 cd ~/cloud/Dropbox/DOCUMENTS/TEMPLATES
 pandoc this_file.org --reference-doc=/home/goyo/cloud/Dropbox/DOCUMENTS/TEMPLATES/DOCX/my_docx_template.docx -o this_file.docx
 soffice --nologo --writer this_file.docx
 #+END_COMMENT

*** LaTeX

# LaTeX specific export settings
# ================================
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
# #+LATEX_CLASS_OPTIONS: [garamond]
# #+LATEX_HEADER: \usepackage{setspace}
# #+LATEX_HEADER: \doublespacing
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage[innermargin=1in,outermargin=0.75in,vmargin=1.5cm]{geometry}
#+LATEX_HEADER: \linespread{1.1}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage[spanish]{babel}


* Método ManBand

Es nuestra actividad habitual nos encontramos gestionando un gran número de
tareas de naturaleza muy diferente. Esta situación genera un gran estrés por lo
que se hace necesaria una forma de gestión que nos ayude disminuir este estrés
afrontando eficientemente el desempeño de las tareas.

Existen numerosas metodologías que han demostrado su efectividad en la gestión
de tareas, así como multitud de herramientas de bajo o ningún coste que
habitualmente se sitúan en la nube.

Precisamente por esta oferta tan abundante, es complicado definir un marco
concreto y único que nos ayude a la gestión de tareas sin que tengamos que
emplear mucho tiempo en el propio aprendizaje y uso de estas metodologías y
herramientas.

En mi caso, llevo enfrentándome a esta problemática desde hace años, tanto en el
ámbito personal como en el profesional. Durante todos estos años he ido
adaptando metodologías y herramientas a mis necesidades que, por otro lado, son
las mismas para otros muchos.

En concreto, he desarrollado un sencillo método basado en conceptos y
metodologías existentes, como GTD y kanban, que he puesto en práctica sobre
varias herramientas como wunderlust, rememberthemilk, trello y Emacs (org).

A este método lo he denominado *manband* u *hombre orquesta* ya que es la principal
sensación que siento cuando me enfrento a la realización de múltiples acciones
que nada tienen entre sí. Gestionar todas esas tareas es como tocar varios
instrumentos a la vez.

Lo cierto es que llevo utilizando este método desde hace muchos años y me ha
servido, y me sirve, para gestionar eficientemente situaciones con muchas tareas
tanto en el ámbito personal como en el profesional.

Este repositorio contiene una [[http://goyoambrosio.com/manband][presentación del método manband]] y de los conceptos
y metodologías en los que se basa.

La presentación está basada en HTML por lo que puede ser visualizada en
cualquier navegador. Está basada en [[https://revealjs.com][Reveal.js]] y ha sido escrita en modo [[https://orgmode.org/][org]] de
[[https://www.gnu.org/software/emacs/][Emacs]] para ser exportada con [[https://github.com/yjwen/org-reveal][org-reveal]]. Un efecto colateral de la misma es que
puede servir de ejemplo para aquellos interesados en estas herramientas.

Espero que te sea de utilidad.

Gregorio Ambrosio (Goyo AC)


